// import global css files
import '@/app/ui/global.css';

// import fonts
// import { Inter } from 'next/font/google';
// const inter = Inter({ subsets: ['latin'] });
import { inter } from '@/app/ui/fonts';

// Define metadata
// export const metadata = {
//   title: 'Create Next app',
//   description: 'Generated by create nect app',
// };

// export const metadata = {
//   title: 'Acme Dashboard',
//   description: 'The official Next.js Course Dashboard, built with App Router.',
//   metadataBase: new URL('https://next-learn-dashboard.vercel.sh'),
// };

export const metadata = {
  title: {
    template: '%s | Acme Dashboard',
    default: 'Acme Dashboard',
  },
  description: 'The official Next.js Learn Dashboard built with App Router.',
  metadataBase: new URL('https://next-learn-dashboard.vercel.sh'),
};

// Define a Root layout function
export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  );
}
